version: '3.8' # Version moderne de Compose

services:
  # 🐘 1. La Base de données PostgreSQL
  db:
    image: postgres:15-alpine # ✅ Version légère et récente
    container_name: postgres-db # ✅ Nom explicite
    restart: always  # ✅ Redémarre automatiquement
    env_file:
      - .env # ✅ Charge les variables depuis .env
    ports:
      - "5433:5432"  # ✅ Évite le conflit si PostgreSQL est installé localement
    volumes:
      - postgres_data:/var/lib/postgresql/data # ✅ Persistance des données

  # ☕ 2. Le Backend Spring Boot (Java 17)
  backend:
    build: .  # 👈 # ✅ Build l'image depuis le Dockerfile local
    image: java-products-lab:1.0 # ✅ Tag l'image
    container_name: java-products-container
    restart: on-failure  # 👈 s'assure que si Java arrive "trop tôt" et crash, il réessaie quelques secondes plus tard, au moment où la DB est enfin prête.
    depends_on:
      - db
    ports:
      - "8082:8082"
    env_file:
      - .env  # ✅ Charge les variables depuis .env
# 💾 3. Définition du volume pour ne pas perdre tes données
volumes:
  postgres_data:
